export const FIND = "FIND";
export const DELETE ='DELETE';
export const LOADING='LOADING';
export const EDIT= 'EDIT';
export const ADD='ADD';
export const RESET='RESET';
export const SEARCH='SEARCH';
export const SAVE='SAVE';
export const SortFliter='SortFliter'